export const constant = {
    ERROR:{
        ERROR_LOGIN:{
            code:0,//人为的修改sessionStorage中的token
            description:'登录状态出现问题,请重新登录',
        },
        NOT_LOGIN:{
            code:1,//未登录
            description:'请登录'
        },
        EXPIRED:{
            code:2,
            description:'登录已过期,请重新登录',
        }
    },
    SUCCESS:{
        code:10001
    },
    TIME_OUT:5000,
    AUTHORIZATION_PROPERTIES:'authorizationProperties',
    SECRET_PROPERTIES:'secretProperties',
    ASSET_STATUS:{
        NORMAL:0,
        APPLyING:1,
        ACCEPT:2
    },
    ASSET_LIST_STATUS:{
        APPLYING:0,
        ACCEPT:1,
        TRANSFERED:2,
        REFUSED:3,
        INVALID:4,
    },
    AUTHORIZATION_STATUS:{
        APPLYING:0,
        AUTH:1,
        REFUSED:2,
        INVALID:3,
        EXPIRED:4
    },
    CHECK_STATUS:{
        NOT_CHECK:0,
        CHECKED:1,
        CHECK_FAILED:2
    }

};